version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: busnotify_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: bus_notification_system
    volumes:
      - mongodb_data:/data/db
      - ./backend/data:/docker-entrypoint-initdb.d
    networks:
      - busnotify_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: busnotify_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - busnotify_network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: busnotify_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/bus_notification_system?authSource=admin
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
      - SECRET_KEY=your-super-secret-key-change-in-production
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    networks:
      - busnotify_network

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: busnotify_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
      - REACT_APP_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - busnotify_network

volumes:
  mongodb_data:
  redis_data:

networks:
  busnotify_network:
    driver: bridge